"""add links table

Revision ID: 2bdbeee4663c
Revises: cafdca975a1c
Create Date: 2026-03-17 20:51:39.634619
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bdbeee4663c'
down_revision: Union[str, None] = 'cafdca975a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='网站名称'),
    sa.Column('url', sa.String(length=500), nullable=False, comment='链接地址'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='简介'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    # ### end Alembic commands ###
