"""init

Revision ID: cafdca975a1c
Revises: 
Create Date: 2026-03-17 10:54:18.370689
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cafdca975a1c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='分类名称'),
    sa.Column('slug', sa.String(length=120), nullable=False, comment='URL 友好标识'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='分类描述'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='标签名称'),
    sa.Column('slug', sa.String(length=60), nullable=False, comment='URL 友好标识'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=200), nullable=False, comment='邮箱'),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False, comment='文章标题'),
    sa.Column('slug', sa.String(length=320), nullable=False, comment='URL 友好标识'),
    sa.Column('content', sa.Text(), nullable=False, comment='Markdown 正文'),
    sa.Column('excerpt', sa.String(length=500), nullable=True, comment='文章摘要（自动截取或手动填写）'),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='浏览量'),
    sa.Column('like_count', sa.Integer(), nullable=False, comment='点赞数'),
    sa.Column('is_published', sa.Boolean(), nullable=False, comment='是否已发布'),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True, comment='全文搜索向量'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='发布时间'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_articles_published_created', 'articles', ['is_published', 'created_at'], unique=False)
    op.create_index('ix_articles_search_vector', 'articles', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('article_tags',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'tag_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父评论 ID，NULL 为顶层评论'),
    sa.Column('author_name', sa.String(length=50), nullable=False, comment='评论者昵称'),
    sa.Column('author_email', sa.String(length=200), nullable=True, comment='评论者邮箱（不公开）'),
    sa.Column('content', sa.Text(), nullable=False, comment='评论内容'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('article_tags')
    op.drop_index('ix_articles_search_vector', table_name='articles', postgresql_using='gin')
    op.drop_index('ix_articles_published_created', table_name='articles')
    op.drop_table('articles')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('categories')
    # ### end Alembic commands ###
